
language: node_js
sudo: required

node_js:
  - "8"

services:
  - docker

before_install:
  - docker-compose -f ci/docker-compose.yml up
  - docker ps -a
  - sleep 30

install:
  - yarn install
  - cp ci/config.json config.json

script: "yarn test"

after_script:
  - docker-compose -f ci/docker-compose.yml down

notifications:
  email: false
