
language: node_js
sudo: required

node_js:
  - "9"

services:
  - docker

before_install:
  - cp ci/docker-compose.yml docker-compose.yml
  - docker-compose up -d
  - docker ps -a
  - sleep 20
  - docker-compose logs

install:
  - yarn install --pure-lockfile

script: "yarn testonly"

after_script:
  - make mrproper

notifications:
  email: false
