
language: node_js
sudo: required

node_js:
  - "9"

services:
  - docker

before_install:
  - cp ci/docker-compose.yml docker-compose.yml
  - docker-compose up -d

install:
  - yarn install --pure-lockfile

script: "yarn testonly"

notifications:
  email: false
