
language: node_js
sudo: required

node_js:
  - "8"

services:
  - docker

before_install:
  - docker-compose -v

install:
  - yarn install
  - cp config.example.json config.json

script: "yarn test"

notifications:
  email: false
