
language: node_js
sudo: required

node_js:
  - "8"

services:
  - docker

before_install:
  - docker-compose -f ci/docker-compose.yml up -d
  - docker ps -a
  - sleep 30

install:
  - yarn install
  - cp config.example.json config.json

script: "yarn test"

notifications:
  email: false
