
language: node_js
sudo: required

node_js:
  - "9"

services:
  - docker

before_install:
  # - cd ci
  # - git clone https://github.com/LiskHQ/lisk.git
  # - docker-compose up --no-start
  # - docker-compose start db
  # - sleep 10
  - docker-compose up -d
  - docker ps -a
  - sleep 60
  # - cd ../

install:
  - yarn install
  # - cp ci/config.json config.json

script: "yarn testonly"

after_script:
  # - cd ci
  - make mrproper

notifications:
  email: false
