
language: node_js
sudo: required

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "9"

services:
  - docker

before_install:
  - cp ci/docker-compose.yml docker-compose.yml
  - docker-compose up -d

install:
  - yarn install --pure-lockfile

script: "yarn test"

notifications:
  email: false
