
language: node_js
sudo: required

node_js:
  - "8"

services:
  - docker

before_install:
  - cd ci
  - wget https://github.com/LiskHQ/lisk-docker/raw/2.1.0/examples/testnet/Makefile
  - make coldstart
  - docker ps -a
  - sleep 60

install:
  - yarn install
  - cp ci/config.json config.json

script: "yarn test"

after_script:
  - cd ci
  - make mrproper

notifications:
  email: false
