FROM node:10-alpine

WORKDIR /app
COPY . ./

RUN yarn install --pure-lockfile \
  && NODE_ENV=production yarn build \
  && yarn install --pure-lockfile --production

ENV PORT=3000

EXPOSE 3000
CMD yarn start
