version: '2'
services:
  lisk:
    image: lisk/core:${LISK_VERSION}
    volumes:
      - lisk-logs:/home/lisk/lisk/logs/
    ports:
      - ${LISK_HTTP_PORT}:${LISK_HTTP_PORT}
      - ${LISK_WS_PORT}:${LISK_WS_PORT}
    networks:
      - lisk
    depends_on:
      - db
    restart: on-failure
    entrypoint:
      ['/home/lisk/wait-for-it.sh', 'db:5432', '--', '/home/lisk/run.sh']
    command: ['-n', '${LISK_NETWORK}']
    environment:
      - LISK_DB_HOST=db
      - LISK_DB_USER=${LISK_DB_USER}
      - LISK_DB_PASSWORD=${LISK_DB_PASSWORD}
      - LISK_DB_DATABASE=${LISK_DB_DATABASE}
      - LISK_CACHEENABLED=false
      - LISK_API_ACCESS_PUBLIC=true

  db:
    image: postgres:10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - lisk
    restart: on-failure
    environment:
      - POSTGRES_DB=${LISK_DB_DATABASE}
      - POSTGRES_PASSWORD=${LISK_DB_PASSWORD}
      - POSTGRES_USER=${LISK_DB_USER}

  task:
    image: postgres:10-alpine
    networks:
      - lisk
    environment:
      - PGUSER=${LISK_DB_USER}
      - PGPASSWORD=${LISK_DB_PASSWORD}
      - PGDATABASE=${LISK_DB_DATABASE}
      - PGHOST=db
    command: /bin/true

  graphql:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - '3000:3000'
    networks:
      - lisk
    depends_on:
      - db
    environment:
      - LISK_DB_HOST=db
      - LISK_DB_USER=${LISK_DB_USER}
      - LISK_DB_PASSWORD=${LISK_DB_PASSWORD}
      - LISK_DB_DATABASE=${LISK_DB_DATABASE}

networks:
  lisk:

volumes:
  db-data:
  lisk-logs:
