version: '2'
services:
  graphql:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - '3000:3000'
    environment:
      - LISK_DB_HOST=${LISK_DB_HOST}
      - LISK_DB_USER=${LISK_DB_USER}
      - LISK_DB_PASSWORD=${LISK_DB_PASSWORD}
      - LISK_DB_DATABASE=${LISK_DB_DATABASE}
