version: '3'
# Add your custom configuration here.
# See README.md for examples.
services:
  lisk:
    environment:
      - LISK_API_PUBLIC=true

  graphql:
    build: ../
    ports:
      - '3000:3000'
    networks:
      - lisk
    depends_on:
      - db
    environment:
      - LISK_DB_HOST=db
      - LISK_DB_USER=${ENV_LISK_DB_USER}
      - LISK_DB_PASSWORD=${ENV_LISK_DB_PASSWORD}
      - LISK_DB_DATABASE=${ENV_LISK_DB_DATABASE}
    volumes:
      - ../:/app/
